--------------------------------------------------------------------------------------
-- MEMBER
--------------------------------------------------------------------------------------

CREATE TABLE MEMBER (
    MEM_NUMBER NUMBER(10),
    MEM_NAME VARCHAR2(20) NOT NULL,
    MEM_NICKNAME VARCHAR2(20)NOT NULL,
    MEM_EMAIL VARCHAR2(30)UNIQUE,
    MEM_PWD VARCHAR2(100) NOT NULL,
    MEM_PHONE VARCHAR2(20) NOT NULL,
    MEM_GENDER VARCHAR2(10) NOT NULL,
    MEM_BDAY VARCHAR2(20) DEFAULT '20000101',
    MEM_ADDRESS VARCHAR2(30) NOT NULL,
    MEM_INTRODUCE VARCHAR2(500) DEFAULT '반갑습니다',
    MEM_STATUS VARCHAR2(10) DEFAULT 'Y'
);

ALTER TABLE MEMBER ADD CONSTRAINT MEM_NUMBER_PK PRIMARY KEY (MEM_NUMBER);

COMMENT ON COLUMN MEMBER.MEM_NUMBER IS '회원번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.MEM_NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEM_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.MEM_GENDER IS '성별';
COMMENT ON COLUMN MEMBER.MEM_BDAY IS '생년월일';
COMMENT ON COLUMN MEMBER.MEM_ADDRESS IS '활동지역';
COMMENT ON COLUMN MEMBER.MEM_INTRODUCE IS '회원소개';
COMMENT ON COLUMN MEMBER.MEM_STATUS IS '상태';

CREATE SEQUENCE SEQ_MNO;

--INSERT INTO MEMBER VALUES (SEQ_MNO.NEXTVAL,?,?,?,?,?,?,?,DEFAULT,DEFAULT);

COMMIT;

--------------------------------------------------------------------------------------
-- board
--------------------------------------------------------------------------------------

CREATE TABLE BOARD (
    BOR_ID NUMBER(10),
    BOR_WRITER_NO NUMBER,
    BOR_WRITER_NAME VARCHAR2(20) NOT NULL,
    BOR_TITLE VARCHAR2(40) NOT NULL,
    BOR_CONTENT VARCHAR2(2000) NOT NULL,
    BOR_NUMBER NUMBER NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    CORRECT_DATE DATE DEFAULT SYSDATE,
    READCOUNT NUMBER DEFAULT 0,
    BOR_STATUS VARCHAR2(5) DEFAULT 'Y',
    ORIGINAL_FILE VARCHAR2(100),
    RENAMED_FILE VARCHAR2(100)
);

ALTER TABLE BOARD ADD CONSTRAINT BOR_ID_PK PRIMARY KEY(BOR_ID);
ALTER TABLE BOARD ADD CONSTRAINT BOR_WRITER_NO_FK FOREIGN KEY(BOR_WRITER_NO) REFERENCES MEMBER(MEM_NUMBER);

COMMENT ON COLUMN BOARD.BOR_ID IS '게시판ID';
COMMENT ON COLUMN BOARD.BOR_WRITER_NO IS '작성자 넘버';
COMMENT ON COLUMN BOARD.BOR_WRITER_NAME IS '작성자 이름';
COMMENT ON COLUMN BOARD.BOR_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOR_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.BOR_NUMBER IS '게시글 번호';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성날짜';
COMMENT ON COLUMN BOARD.CORRECT_DATE IS '수정날짜';
COMMENT ON COLUMN BOARD.READCOUNT IS '조회수';
COMMENT ON COLUMN BOARD.BOR_STATUS IS '상태';
COMMENT ON COLUMN BOARD.ORIGINAL_FILE IS '첨부파일원래이름';
COMMENT ON COLUMN BOARD.RENAMED_FILE IS '첨부파일변경이름';


COMMIT;