-- 회원테이블
CREATE TABLE MEMBER (
    MEM_NUMBER NUMBER(10),
    MEM_NAME VARCHAR2(20) NOT NULL,
    MEM_NICKNAME VARCHAR2(20)NOT NULL,
    MEM_EMAIL VARCHAR2(30)UNIQUE,
    MEM_PWD VARCHAR2(100) NOT NULL,
    MEM_PHONE VARCHAR2(20) NOT NULL,
    MEM_GENDER VARCHAR2(10) NOT NULL,
    MEM_BDAY VARCHAR2(20) DEFAULT '20000101',
    MEM_ADDRESS VARCHAR2(30) NOT NULL,
    MEM_INTRODUCE VARCHAR2(500) DEFAULT '반갑습니다',
    MEM_STATUS VARCHAR2(10) DEFAULT 'Y',
    MEM_MY_PLOGING VARCHAR2(30) DEFAULT '플로깅모임없음'
);
ALTER TABLE MEMBER ADD CONSTRAINT MEM_NUMBER_PK PRIMARY KEY (MEM_NUMBER);

CREATE SEQUENCE SEQ_MNO;

-- 개인인증게시판
CREATE TABLE INDIBOARD (
    INDIBOR_NUMBER NUMBER, 
    INDIBOR_WRITER_NO NUMBER,
    INDIBOR_WRITER_NAME VARCHAR2(20) NOT NULL, 
    INDIBOR_TITLE VARCHAR2(100),
    INDIBOR_CONTENT VARCHAR2(1000),
    INDI_CREATE_DATE DATE DEFAULT SYSDATE,
    INDI_UPDATE_DATE DATE DEFAULT SYSDATE,
    INDI_READCOUNT NUMBER DEFAULT 0,
    INDI_BOR_FILE VARCHAR2(100),
    INDI_BOR_STATUS VARCHAR2(5) DEFAULT 'Y',
    INDI_BOR_KEYWORD VARCHAR2(50) DEFAULT '플로깅'
);
ALTER TABLE INDIBOARD ADD CONSTRAINT INDIBOR_NUMBER_PK PRIMARY KEY(INDIBOR_NUMBER);
ALTER TABLE INDIBOARD ADD CONSTRAINT INDIBOR_WRITER_NO FOREIGN KEY(INDIBOR_WRITER_NO) REFERENCES MEMBER(MEM_NUMBER);

CREATE SEQUENCE SEQ_INDIBOR_NUMBER;

-- 개인인증게시판 댓글테이블
CREATE TABLE IBREPLY(
  IBREP_NUMBER NUMBER,
  IBREP_BOR_NUMBER NUMBER,
  IBREP_WRITER_NUMBER NUMBER,
  IBREP_CONTENT VARCHAR2(400),
  IBREP_STATUS VARCHAR2(1) DEFAULT 'Y',
  IBREP_CREATE_DATE DATE DEFAULT SYSDATE,
  IBREP_MODIFY_DATE DATE DEFAULT SYSDATE
);
ALTER TABLE IBREPLY ADD CONSTRAINT IBREP_NUMBER_PK PRIMARY KEY(IBREP_NUMBER);
ALTER TABLE IBREPLY ADD CONSTRAINT IBREP_BOR_NUMBER_FK FOREIGN KEY(IBREP_BOR_NUMBER) REFERENCES INDIBOARD(INDIBOR_NUMBER);
ALTER TABLE IBREPLY ADD CONSTRAINT IBREP_WRITER_NUMBER_FK FOREIGN KEY(IBREP_WRITER_NUMBER) REFERENCES MEMBER(MEM_NUMBER);

CREATE SEQUENCE SEQ_IBREP_NUMBER;

-- 플로깅모임검색게시판
CREATE TABLE SEARCH_PLOG_BOARD(
    SPBOR_NUMBER NUMBER, -- 플로깅모임번호
    SPB_WRITER_NO NUMBER,
    SPB_WRITER_NAME VARCHAR2(20) NOT NULL,
    PLOG_GROUP_NAME VARCHAR2(50) NOT NULL, --멤버테이블 MY_PLOGING
    SPB_TITLE VARCHAR2(100),
    SPB_CONTENT VARCHAR2(1000),
    SPB_CREATE_DATE DATE DEFAULT SYSDATE,
    SPB_UPDATE_DATE DATE DEFAULT SYSDATE,
    SPB_READCOUNT NUMBER DEFAULT 0,
    SPB_BOR_FILE VARCHAR2(100),
    SPB_BOR_STATUS VARCHAR2(5) DEFAULT 'Y',
    SPB_BOR_KEYWORD VARCHAR2(50) DEFAULT '플로깅'
);

ALTER TABLE SEARCH_PLOG_BOARD ADD CONSTRAINT SPBOR_NUMBER_PK PRIMARY KEY(SPBOR_NUMBER);
ALTER TABLE SEARCH_PLOG_BOARD ADD CONSTRAINT SPB_WRITER_NO_FK FOREIGN KEY(SPB_WRITER_NO) REFERENCES MEMBER(MEM_NUMBER);
CREATE SEQUENCE SEQ_SPBOR_NUMBER;

DROP TABLE MEMBER;
DROP TABLE INDIBOARD;
DROP TABLE IBREPLY;
DROP TABLE SEARCH_PLOG_BOARD;



CREATE TABLE PG_NOTICE(
  NOTICE_NUMBER NUMBER,
  NOTICE_BOR_NUMBER NUMBER,
  NOTICE_WRITER_NUMBER NUMBER,
  NOTICE_CONTENT VARCHAR2(400),
  NOTICE_STATUS VARCHAR2(1) DEFAULT 'Y',
  NOTICE_CREATE_DATE DATE DEFAULT SYSDATE,
  NOTICE_MODIFY_DATE DATE DEFAULT SYSDATE
);
INSERT INTO PG_NOTICE VALUES(SEQ_NOTICE_NUMBER.NEXTVAL, 26, 83, '내용', DEFAULT, DEFAULT, DEFAULT);
ALTER TABLE PG_NOTICE ADD CONSTRAINT NOTICE_NUMBER_PK PRIMARY KEY(NOTICE_NUMBER);
ALTER TABLE PG_NOTICE ADD CONSTRAINT NOTICE_BOR_NUMBER_FK FOREIGN KEY(NOTICE_BOR_NUMBER) REFERENCES SEARCH_PLOG_BOARD(SPBOR_NUMBER);
ALTER TABLE PG_NOTICE ADD CONSTRAINT NOTICE_WRITER_NUMBER_FK FOREIGN KEY(NOTICE_WRITER_NUMBER) REFERENCES MEMBER(MEM_NUMBER);

CREATE SEQUENCE SEQ_NOTICE_NUMBER;
DROP TABLE PG_NOTICE;

CREATE TABLE GBREPLY(
  GBREP_NUMBER NUMBER,
  GBREP_BOR_NUMBER NUMBER,
  GBREP_WRITER_NUMBER NUMBER,
  GBREP_CONTENT VARCHAR2(400),
  GBREP_STATUS VARCHAR2(1) DEFAULT 'Y',
  GBREP_CREATE_DATE DATE DEFAULT SYSDATE,
  GBREP_MODIFY_DATE DATE DEFAULT SYSDATE
);
ALTER TABLE GBREPLY ADD CONSTRAINT GBREP_NUMBER_PK PRIMARY KEY(GBREP_NUMBER);
ALTER TABLE GBREPLY ADD CONSTRAINT GBREP_BOR_NUMBER_FK FOREIGN KEY(GBREP_BOR_NUMBER) REFERENCES GROUPBOARD(GROUPBOR_NUMBER);
ALTER TABLE GBREPLY ADD CONSTRAINT GBREP_WRITER_NUMBER_FK FOREIGN KEY(GBREP_WRITER_NUMBER) REFERENCES MEMBER(MEM_NUMBER);

CREATE SEQUENCE SEQ_GBREP_NUMBER;

CREATE TABLE GROUPBOARD (
    GROUPBOR_NUMBER NUMBER, -- 전체 게시글 번호
    GROUPBOR_WRITER_NO NUMBER, -----작성자 ID
    GROUPBOR_WRITER_NAME VARCHAR2(20) NOT NULL, ----작성자
    GROUPBOR_TITLE VARCHAR2(100), ---제목
    GROUPBOR_CONTENT VARCHAR2(1000),----내용
    GROUP_CREATE_DATE DATE DEFAULT SYSDATE,
    GROUP_UPDATE_DATE DATE DEFAULT SYSDATE,
    GROUP_READCOUNT NUMBER DEFAULT 0,
    GROUP_BOR_FILE VARCHAR2(100), -----
    GROUP_BOR_STATUS VARCHAR2(5) DEFAULT 'Y',
    GROUP_BOR_KEYWORD VARCHAR2(50) DEFAULT '플로깅'
);

ALTER TABLE GROUPBOARD ADD GROUPBOR_GROUPNAME VARCHAR(100);
ALTER TABLE GROUPBOARD ADD CONSTRAINT GROUPBOR_NUMBER_PK PRIMARY KEY(GROUPBOR_NUMBER);
ALTER TABLE GROUPBOARD ADD CONSTRAINT GROUPBOR_WRITER_NO FOREIGN KEY(GROUPBOR_WRITER_NO) REFERENCES MEMBER(MEM_NUMBER);

CREATE SEQUENCE SEQ_GROUPBOR_NUMBER;


DROP TABLE GROUPBOARD;
DROP TABLE GBREPLY;




































































